### ISSUE TITLE
Tex编译报错

### ISSUE THREAD

**Issue by TwistedW** [netcan/HFUT_Thesis#3]
未做任何修改情况下Latex编译错误
<img width="498" alt="image" src="https://user-images.githubusercontent.com/24953417/73732643-7fda9a80-4775-11ea-97f5-6dfb6fc84aaf.png">

**Comment by netcan** [comment]
用初始版可以么？
https://github.com/netcan/HFUT_Thesis/releases

**Comment by TwistedW** [comment]
我改好了，可能是我环境配置的问题了，很感谢回答
